export const categoryImages: {[key: string]: any} = {
  beauty: require('../../assets/images/Categories/beauty.jpg'),
  fragrances: require('../../assets/images/Categories/fragrances.jpg'),
  furniture: require('../../assets/images/Categories/furniture.jpg'),
  groceries: require('../../assets/images/Categories/groceries.jpg'),
  'home-decoration': require('../../assets/images/Categories/home-decoration.jpg'),
  'kitchen-accessories': require('../../assets/images/Categories/kitchen-accessories.jpg'),
  laptops: require('../../assets/images/Categories/laptops.jpg'),
  'mens-shirts': require('../../assets/images/Categories/mens-shirts.jpg'),
  'mens-shoes': require('../../assets/images/Categories/mens-shoes.jpg'),
  'mens-watches': require('../../assets/images/Categories/mens-watches.jpg'),
  'mobile-accessories': require('../../assets/images/Categories/mobile-accessories.jpg'),
  motorcycle: require('../../assets/images/Categories/motorcycle.jpg'),
  'skin-care': require('../../assets/images/Categories/skin-care.jpg'),
  smartphones: require('../../assets/images/Categories/smartphones.jpg'),
  'sports-accessories': require('../../assets/images/Categories/sports-accessories.jpg'),
  sunglasses: require('../../assets/images/Categories/sunglasses.jpg'),
  tablets: require('../../assets/images/Categories/tablets.jpg'),
  tops: require('../../assets/images/Categories/tops.jpg'),
  vehicle: require('../../assets/images/Categories/vehicle.jpg'),
  'womens-bags': require('../../assets/images/Categories/womens-bags.jpg'),
  'womens-dresses': require('../../assets/images/Categories/womens-dresses.jpg'),
  'womens-jewellery': require('../../assets/images/Categories/womens-jewellery.jpg'),
  'womens-shoes': require('../../assets/images/Categories/womens-shoes.jpg'),
  'womens-watches': require('../../assets/images/Categories/womens-watches.jpg'),
};
